#!/bin/bash
# Author: https://github.com/estesp/manifest-tool/blob/master/integration/test-registry.sh

_REGISTRY="${1}"

_IMAGELIST="s390x/alpine
ppc64le/alpine
aarch64/alpine
alpine"

[ -z "${_REGISTRY}" ] && {
	echo "Please provide a registry URL + namespace/repo name as the first parameter"
	exit 1
}

echo "Warning: some commands will fail if you are not authenticated to ${_REGISTRY}"

echo ">> 1: Pulling required images from DockerHub"
for i in $_IMAGELIST; do
	docker pull ${i}:latest
done

echo ">> 2: Tagging and pushing images to registry ${_REGISTRY}"
for i in $_IMAGELIST; do
	target="${i/\//_}"
	[ "${target}" == "${i}" ] && {
		# special case for no arch prefix on amd64 (x86_64 Linux) images  
		target="amd64_${i}"
	}
	echo docker tag ${i}:latest ${_REGISTRY}/${target}:latest
	docker tag ${i}:latest ${_REGISTRY}/${target}:latest
	docker push ${_REGISTRY}/${target}:latest
done

echo ">> 4: Attempt creating manifest list on registry ${_REGISTRY}"

sed s,__REGISTRY__,${_REGISTRY}, test-registry.yml >test-registry.yaml
manifest-tool --debug push from-spec test-registry.yaml
